### ISSUE TITLE
Allow for changing ip address

### ISSUE THREAD

**Issue by jaypz** [luminus-framework/luminus-http-kit#1]
Hi, I hope filing issues here is welcome

I would really like to be able to toggle what IP address the application is bound on right now it 0.0.0.0 http-kit supports an ip argument it would be really helpful to allow users to toggle this.

https://github.com/http-kit/http-kit/blob/master/src/org/httpkit/server.clj#L17

**Comment by yogthos** [comment]
thanks for the fix, I'll do a push shortly https://github.com/luminus-framework/luminus-http-kit/pull/2
